### ISSUE TITLE
remote tuning: Warning: Failed to get value for OutputChannel: tuneCrc16

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#80]
Scenario 1:
real discovery
rusEFI proxy
connector
rusEFI console connects just fine, gauges are alive

Scenario 2:
real discovery
rusEFI proxy
connector
TunerStudio reads out configurations and disconnects :(
in the logs

```
7/24/20 1:20:29 AM :Debug: isBlank Time: 0 ms.
7/24/20 1:20:29 AM :Debug: Read All Data
7/24/20 1:20:29 AM :Debug: Time:8.123s. Processing Complete: Read All Tune Data
7/24/20 1:20:29 AM :Debug: Real OchDelay for dev: 50, timeout=300
7/24/20 1:20:29 AM :Time: 0:08.124: SENT 11 bytes, 11 bytes
x00 x05 x4F x00 x00 xF2 x00 x3A x0B xBB xBA                           ..O....:...

7/24/20 1:20:29 AM :Debug: DiffTime: 12 ms.
7/24/20 1:20:29 AM :Time: 0:08.251: READ 3 bytes, 3 bytes
x00 xF3 x00                                                           ...

7/24/20 1:20:29 AM :Debug: Blocked time to read outpc: 127 ms.
7/24/20 1:20:29 AM :Time: 0:08.251: READ 246 bytes, 246 bytes
x86 x04 x01 x02 x00 x00 x00 x00 x00 x00 x00 x25 xE3 x11 x31 x11       ...........%..1.
x00 x00 x00 x00 x0D x07 x00 x00 xB4 x00 x00 x00 x00 x00 xF3 x04       ................
x00 x00 x23 x27 x82 x10 xA9 x13 x00 x00 x00 x00 xB7 x00 x00 x00       ..#'............
xB0 x36 x65 x06 xC7 x06 x00 x00 x00 x9F x78 x69 xA7 x11 xF3 x03       .6e.......xi....
x64 x00 x69 x00 x64 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       d.i.d...........
x00 x00 x00 x00 x4A x02 xB0 x04 x00 x00 xDC x18 x00 x00 x00 x00       ....J...........
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
xCD x18 x00 x00 x34 x00 x00 x00 x14 x3D x34 x01 x76 x3B x34 x01       ....4....=4.v;4.
x00 x00 x00 x00 x00 x00 x5D x10 x5D x10 x3B x1F x00 x00 x00 x00       ......].].;.....
x00 x00 x00 x00 xE3 x66 x40 x1F x40 x1F x00 x00 x00 x00 x00 x00       .....f@.@.......
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x00 x00 x19 xFC x19 xFC x19 xFC x19 xFC       ................
x19 xFC x19 xFC x19 xFC x19 xFC x00 x00 x86 x03 x00 x00 xDB x04       ................
x19 x05 xFC xA3 xD8 xBF                                               ......

7/24/20 1:20:29 AM :Warning: Failed to get value for OutputChannel: tuneCrc16 using och:x86 x04 x01 x02 x00 x00 x00 x00 x00 x00 x00 x25 xE3 x11 x31 x11       ...........%..1.
x00 x00 x00 x00 x0D x07 x00 x00 xB4 x00 x00 x00 x00 x00 xF3 x04       ................
x00 x00 x23 x27 x82 x10 xA9 x13 x00 x00 x00 x00 xB7 x00 x00 x00       ..#'............
xB0 x36 x65 x06 xC7 x06 x00 x00 x00 x9F x78 x69 xA7 x11 xF3 x03       .6e.......xi....
x64 x00 x69 x00 x64 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       d.i.d...........
x00 x00 x00 x00 x4A x02 xB0 x04 x00 x00 xDC x18 x00 x00 x00 x00       ....J...........
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
xCD x18 x00 x00 x34 x00 x00 x00 x14 x3D x34 x01 x76 x3B x34 x01       ....4....=4.v;4.
x00 x00 x00 x00 x00 x00 x5D x10 x5D x10 x3B x1F x00 x00 x00 x00       ......].].;.....
x00 x00 x00 x00 xE3 x66 x40 x1F x40 x1F x00 x00 x00 x00 x00 x00       .....f@.@.......
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
x00 x00 x00 x00 x00 x00 x00 x00 x19 xFC x19 xFC x19 xFC x19 xFC       ................
x19 xFC x19 xFC x19 xFC x19 xFC x00 x00 x86 x03 x00 x00 xDB x04       ................
x19 x05                                                               ..
7/24/20 1:20:29 AM :Info: dr: 0:132
7/24/20 1:20:29 AM :Info: dr: 244:245
7/24/20 1:20:29 AM :Debug: Real OchDelay for dev: 50, timeout=300
7/24/20 1:20:29 AM :Time: 0:08.258: SENT 11 bytes, 11 bytes
x00 x05 x4F x00 x00 x85 x00 x5A x75 x54 x8B                           ..O....ZuT.

7/24/20 1:20:29 AM :Time: 0:08.271: READ 3 bytes, 3 bytes
x00 x86 x00                                                           ...

7/24/20 1:20:29 AM :Time: 0:08.271: READ 137 bytes, 137 bytes
x86 x04 x01 x02 x00 x00 x00 x00 x00 x00 x00 x25 x05 x12 x1D x11       ...........%....
x00 x00 x00 x00 x21 x07 x00 x00 xB6 x00 x00 x00 x00 x00 xEF x04       ....!...........
x00 x00 x23 x27 x73 x10 x9D x13 x00 x00 x00 x00 xBA x00 x00 x00       ..#'s...........
xB0 x36 x85 x06 xE9 x06 x00 x00 x00 x9F x78 x69 xA4 x11 xF3 x03       .6........xi....
x64 x00 x69 x00 x64 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       d.i.d...........
x00 x00 x00 x00 x49 x02 xB0 x04 x00 x00 xD7 x18 x00 x00 x00 x00       ....I...........
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
xCD x18 x00 x00 x34 x00 x00 x00 x14 x3D x34 x01 x76 x3B x34 x01       ....4....=4.v;4.
x00 x00 x00 x00 x00 xD6 x88 x7C xAE                                   .......|.

7/24/20 1:20:29 AM :Time: 0:08.271: SENT 11 bytes, 11 bytes
x00 x05 x4F xF4 x00 x02 x00 x27 xB3 xDB xF7                           ..O....'...

7/24/20 1:20:29 AM :Time: 0:08.287: READ 3 bytes, 3 bytes
x00 x03 x00                                                           ...

7/24/20 1:20:29 AM :Time: 0:08.287: READ 6 bytes, 6 bytes
x46 xB0 x92 x03 x82 x1D                                               F.....

7/24/20 1:20:29 AM :Debug: Comm Exception Caught: null
Jul 24, 2020 1:20:29 AM y.s run
WARNING: Comm Timeout Caught
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at F.J.b(Unknown Source)
	at F.J.z(Unknown Source)
	at y.r.e(Unknown Source)
	at y.s.run(Unknown Source)

7/24/20 1:20:30 AM :Debug: No Remaining Queue Write instructions
7/24/20 1:20:31 AM :Debug: Real OchDelay for dev: 50, timeout=300
7/24/20 1:20:31 AM :Time: 0:09.790: SENT 11 bytes, 11 bytes
x00 x05 x4F x00 x00 x85 x00 x5A x75 x54 x8B                           ..O....ZuT.

7/24/20 1:20:31 AM :Time: 0:09.867: READ 3 bytes, 3 bytes
x00 x86 x00                                                           ...

7/24/20 1:20:31 AM :Time: 0:09.867: READ 137 bytes, 137 bytes
x86 x04 x01 x02 x00 x00 x00 x00 x00 x00 x00 x25 xDF x11 x36 x11       ...........%..6.
x00 x00 x00 x00 x0D x07 x00 x00 xB4 x00 x00 x00 x00 x00 x01 x05       ................
x00 x00 x23 x27 xAE x10 xBC x13 x00 x00 x00 x00 xB7 x00 x00 x00       ..#'............
xB0 x36 x68 x06 xCA x06 x00 x00 x00 x9F x78 x69 xA3 x11 xF3 x03       .6h.......xi....
x64 x00 x69 x00 x64 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       d.i.d...........
x00 x00 x00 x00 x4A x02 xB0 x04 x00 x00 xD3 x18 x00 x00 x00 x00       ....J...........
x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00 x00       ................
xCF x18 x00 x00 x34 x00 x00 x00 x14 x3D x34 x01 x76 x3B x34 x01       ....4....=4.v;4.
x00 x00 x00 x00 x00 xE1 x9A x35 x9A                                   .......5.

7/24/20 1:20:31 AM :Time: 0:09.867: SENT 11 bytes, 11 bytes
x00 x05 x4F xF4 x00 x02 x00 x27 xB3 xDB xF7                           ..O....'...

7/24/20 1:20:31 AM :Time: 0:09.881: READ 3 bytes, 3 bytes
x00 x03 x00                                                           ...

7/24/20 1:20:31 AM :Time: 0:09.881: READ 6 bytes, 6 bytes
x46 xB0 x92 x03 x82 x1D                                               F.....

7/24/20 1:20:31 AM :Debug: Comm Exception Caught: null
Jul 24, 2020 1:20:31 AM y.s run
WARNING: Comm Timeout Caught
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at F.J.b(Unknown Source)
	at F.J.z(Unknown Source)
	at y.r.e(Unknown Source)
	at y.s.run(Unknown Source)

7/24/20 1:20:32 AM :Debug: controllerOnline = 0.0
7/24/20 1:20:32 AM :Debug: No Remaining Queue Write instructions
7/24/20 1:20:32 AM :Debug: Went offline
7/24/20 1:20:32 AM :Debug: controllerOnline = 0.0
7/24/20 1:20:32 AM :Debug: Deactivated fast paint Main Dashboard
7/24/20 1:20:32 AM :Debug: No Remaining Queue Write instructions
7/24/20 1:20:32 AM :Info: Went offline 2
Jul 24, 2020 1:20:32 AM y.s run
INFO: Inside read error
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at F.J.b(Unknown Source)
	at F.J.z(Unknown Source)
	at y.r.e(Unknown Source)
	at y.s.run(Unknown Source)

7/24/20 1:20:34 AM :Info: Time to save msq: 78.95307
7/24/20 1:20:34 AM :Info: closeApp Called
7/24/20 1:20:34 AM :Info: Slave Server Deactivated.
7/24/20 1:20:34 AM :Debug: TuneLog Editor set text
7/24/20 1:20:34 AM :Debug: Opening Connection to TCP Device: localhost:29001
7/24/20 1:20:34 AM :Time: 0:13.021: SENT 1 bytes, 1 bytes
x46                                                                   F

7/24/20 1:20:34 AM :Debug: Fill Constants: 43
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: An .msq value was null??? This shouldn't happen.
7/24/20 1:20:34 AM :Debug: File does not exist, creating new:
C:\Users\Huge\Documents\TunerStudioProjects\dev\restorePoints\dev_2020-07-24_01.20.34.msq
7/24/20 1:20:34 AM :Info: Time to save msq: 15.537821
7/24/20 1:20:34 AM :Info: dev Restore point saved
7/24/20 1:20:34 AM :Info: dev Restore point saved to: dev_2020-07-24_01.20.34.msq
7/24/20 1:20:34 AM :Info: Time to save msq: 9.773871
7/24/20 1:20:34 AM :Debug: goOffline Starting, Time:0
7/24/20 1:20:34 AM :Info: Deactivated Turbo Baud, goOffline
7/24/20 1:20:34 AM :Debug: goOffline about to stopProcessing, Time:0
7/24/20 1:20:34 AM :Debug: goOffline closed port, Time:0
7/24/20 1:20:34 AM :Time: 0:13.271: READ 3 bytes, 3 bytes
x30 x30 x31                                                           001

7/24/20 1:20:34 AM :Time: 0:13.271: SENT 7 bytes, 7 bytes
x00 x01 x53 x20 x60 xEF xC3                                           ..S.`..

7/24/20 1:20:35 AM :Time: 0:14.271: READ 3 bytes, 3 bytes
x00 x22 x00                                                           .".

7/24/20 1:20:35 AM :Time: 0:14.271: READ 37 bytes, 37 bytes
x72 x75 x73 x45 x46 x49 x20 x32 x30 x32 x30 x2E x30 x37 x2E x32       rusEFI.2020.07.2
x33 x2E x61 x6C x6C x2E x31 x32 x34 x31 x34 x31 x38 x30 x31 x33       3.all.1241418013
x00 xBE xDD xFA xD0                                                   .....

7/24/20 1:20:35 AM :Info: Sig Bytes:x72 x75 x73 x45 x46 x49 x20 x32 x30 x32 x30 x2E x30 x37 x2E x32       rusEFI.2020.07.2
x33 x2E x61 x6C x6C x2E x31 x32 x34 x31 x34 x31 x38 x30 x31 x33       3.all.1241418013
x00                                                                   .
7/24/20 1:20:35 AM :Time: 0:14.272: SENT 7 bytes, 7 bytes
x00 x01 x56 x50 x0A x1B x4C                                           ..VP..L

7/24/20 1:20:36 AM :Time: 0:15.272: READ 3 bytes, 3 bytes
x00 x18 x00                                                           ...

7/24/20 1:20:36 AM :Time: 0:15.272: READ 27 bytes, 27 bytes
x72 x75 x73 x45 x46 x49 x20 x76 x32 x30 x32 x30 x30 x37 x32 x34       rusEFI.v20200724
x40 x32 x34 x35 x31 x38 x00 x26 x2F xC2 x7A                           @24518.&/.z

7/24/20 1:20:36 AM :Info: Communicating with sig:rusEFI 2020.07.23.all.1241418013, rusEFI v20200724@24518
7/24/20 1:20:39 AM :Debug: goOffline comm thread stopped, Time:5000
7/24/20 1:20:39 AM :Debug: No Remaining Queue Write instructions
7/24/20 1:20:39 AM :Debug: removing Configuration: dev
7/24/20 1:20:39 AM :Debug: ############################################# Save Project ##########################################
7/24/20 1:20:39 AM :Info: Finalizing Sensors
Saved user properties successfully

**Comment by rusefillc** [comment]
[TunerStudioAppDebug.zip](https://github.com/rusefi/web_backend/files/4970303/TunerStudioAppDebug.zip)

**Comment by rusefillc** [comment]
resolved by using proper project file. once signature matched outputs started to work!
