### ISSUE TITLE
rusEFI generated tunes are broken - empty string

### ISSUE THREAD

**Issue by rusefillc** [rusefi/web_backend#89]
https://rusefi.com/online/view.php?msq=89 which is https://rusefi.com/online/ini/rusefi/2020/07/21/mre_f4/ seems to be broken

```
Nested Exception - Root cause:
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at bB.M.a(Unknown Source)
	at bB.M.a(Unknown Source)
	at V.Y.a(Unknown Source)
	at V.Y.a(Unknown Source)
	at aI.g.a(Unknown Source)
	at aI.g.a(Unknown Source)
	at aI.g.a(Unknown Source)
	at aI.dX.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)

```

**Comment by rusefillc** [comment]
problem is with 2nd line of the XML file

it should be
``<msq xmlns="http://www.msefi.com/:msq">``

but somehow it's not?!

need to start wring more info into those files line console version and JRE version and etc :(

**Comment by rusefillc** [comment]
maybe the problem:
looks like RE write pcVariables as constants:

```
        <constant digits="0" name="tsCanId" units="">"0"</constant>
        <constant digits="0" name="tuneCrcPcVariable" units=""/>
        <constant digits="1" name="wueAfrTargetOffset" units=":1">
	 -1.5
	 -1.4000000000000001
	 -1.1
	 -0.9
	 -0.8
	 -0.6000000000000001
	 -0.6000000000000001
	 -0.5
	 -0.4
	 -0.4
	 -0.30000000000000004
	 -0.2
	 -0.2
	 -0.1
	 -0.1
	 0.0
</constant>
        <constant digits="0" name="wueAnalRecommend" units="%">
	 2.0
	 2.0
	 1.0
	 1.0
	 1.0
	 1.0
	 1.0
	 1.0
	 1.0
	 1.0
	 1.0
	 1.0
	 1.0
	 1.0
	 1.0
	 1.0
</constant>
        <constant digits="0" name="enableLogDebugChannels" units="">"Yes"</constant>
        <constant digits="0" name="enableLogErrorList" units="">"Yes"</constant>
        <constant digits="0" name="debugFieldF1List" units="">"Controller Output"</constant>
        <constant digits="0" name="debugFieldF2List" units="">"I-Term"</constant>
        <constant digits="0" name="debugFieldF3List" units="">"Previous Error"</constant>
        <constant digits="0" name="debugFieldF4List" units="">"I Gain"</constant>
        <constant digits="0" name="debugFieldF5List" units="">"D Gain"</constant>
        <constant digits="0" name="debugFieldF6List" units="">"D Term"</constant>
        <constant digits="0" name="debugFieldF7List" units="">"Max-Value"</constant>
        <constant digits="0" name="debugFieldI1List" units="">"P-Gain"</constant>
        <constant digits="0" name="debugFieldI2List" units="">"Offset"</constant>
        <constant digits="0" name="debugFieldI3List" units="">"Reset Cnt"</constant>
        <constant digits="0" name="debugFieldI4List" units="">"Period"</constant>
        <constant digits="0" name="debugFieldI5List" units="">""</constant>
        <constant digits="0" name="engineType" units="">"FORD_INLINE_6_1995"</constant>
        <constant digits="0" name="engineSnifferRpmThreshold" units="RPM">2500.0</constant>
        <constant digits="2" name="injector_flow" units="cm3/min">230.0</constant>
        <constant digits="2" name="injector_battLagCorrBins" units="volts">
	 6.0
	 8.0
	 10.0
	 11.0
	 12.0
	 13.0
	 14.0
	 15.0
</constant>

```

**Comment by rusefillc** [comment]
@andreika-git need help identifying the issue :( i've fixed a couple of things but still https://rusefi.com/online/view.php?msq=93 would not be consumed by TS. Do you see any problems with that file? Does the stacktrace help?

**Comment by rusefillc** [comment]
this is now resolved with Phil's help
